// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAp_eKEzN227_g1bHXulRC63KJw9Vp84Ek',
    appId: '1:9670766431:web:fab5b165cfee1fcb1750ea',
    messagingSenderId: '9670766431',
    projectId: 'sensor-75cb9',
    authDomain: 'sensor-75cb9.firebaseapp.com',
    storageBucket: 'sensor-75cb9.appspot.com',
    measurementId: 'G-P2WPNNT02E',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyB7BzlN7pgOpvqcZ7uTRivejTQsUy2ffd8',
    appId: '1:9670766431:android:488110df000506281750ea',
    messagingSenderId: '9670766431',
    projectId: 'sensor-75cb9',
    storageBucket: 'sensor-75cb9.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDJDaXRHpZAdqVfdG4krVRVZdYsEa1Zesg',
    appId: '1:9670766431:ios:39c2b6aadf1f81c21750ea',
    messagingSenderId: '9670766431',
    projectId: 'sensor-75cb9',
    storageBucket: 'sensor-75cb9.appspot.com',
    iosBundleId: 'com.example.latest',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDJDaXRHpZAdqVfdG4krVRVZdYsEa1Zesg',
    appId: '1:9670766431:ios:39c2b6aadf1f81c21750ea',
    messagingSenderId: '9670766431',
    projectId: 'sensor-75cb9',
    storageBucket: 'sensor-75cb9.appspot.com',
    iosBundleId: 'com.example.latest',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyAp_eKEzN227_g1bHXulRC63KJw9Vp84Ek',
    appId: '1:9670766431:web:6f440b4bd6d48e9a1750ea',
    messagingSenderId: '9670766431',
    projectId: 'sensor-75cb9',
    authDomain: 'sensor-75cb9.firebaseapp.com',
    storageBucket: 'sensor-75cb9.appspot.com',
    measurementId: 'G-EXR0MPYMLB',
  );
}
